Oscar/create card
oscar-cuellar/unit-converter pull request #2
Opened 2024-02-11 01:20 UTC by oscar-cuellar

1. Se creo la estructura inicial del proyecto.
2. Se creo los imputs, selects y parte del CSS del proyecto.
<img width="220" alt="Captura de pantalla 2024-02-10 210921" src="https://github.com/oscar-cuellar/unit-converter/assets/43726366/c5c1c374-7c8c-48e6-b105-49996533c4b4">

2024-02-11 01:31 UTC, alan-serrano requested changes

2024-02-11 01:31 UTC, alan-serrano commented on index.html
> +          <option value="0.001|0|km">Kilómetro (km)</option>
Esto es mock data? Añadir un TODO para recordar que se tiene que eliminar esta parte del código cuando se tenga los datos. O mejor aún no incluirla en el PR para code review

2024-02-11 01:31 UTC, alan-serrano commented on index.html
> +        <div class="result_container mini_result_container">
Qué hace esta parte del html?

2024-02-11 01:31 UTC, alan-serrano commented on src/css/styles.css
> +    width: 216px;
Esto es sólo para desktop? se creará otro ticket para mobile?

2024-02-11 01:31 UTC, alan-serrano commented on src/css/styles.css
> +}
nit: Es buena práctica añadir un salto de línea al final del archivo

2024-02-11 01:31 UTC, alan-serrano commented on src/css/styles.css
> +    font-family: inherit;
Este css es necesario?

2024-02-11 01:31 UTC, alan-serrano commented on src/css/styles.css
> +    line-height: 1.1;
Por qué un line-height de 1.1?

2024-02-11 01:31 UTC, alan-serrano commented on src/css/styles.css
> +    margin: 0 39px 24px 0;
Este margin no es necesario, se puede usar display flex cuando se creen las demás tarjetas

2024-02-11 01:31 UTC, alan-serrano commented on index.html
> +        <input><br>
Es necesario el br? tal vez sea mejor encapsular el input en un div

2024-02-11 01:31 UTC, alan-serrano commented on index.html
> +          <option disabled="disabled">&nbsp;</option>
Esta opción al final es necesaria?

2024-02-11 01:46 UTC, alan-serrano requested changes

2024-02-11 01:46 UTC, alan-serrano commented on index.html
> +        </div>
Qué hace esta parte del html?

2024-02-11 13:26 UTC, oscar-cuellar commented on index.html
> +        <input><br>
Corregido, gracias por la observación.

2024-02-11 13:34 UTC, oscar-cuellar commented on index.html
> +          <option value="0.001|0|km">Kilómetro (km)</option>
Listado en TODO!

2024-02-11 13:38 UTC, oscar-cuellar commented on index.html
> +          <option disabled="disabled">&nbsp;</option>
Se elimino las opciones, se decidió quitar el espacio final, esta opción solo servía para dar un espacio.

2024-02-11 14:04 UTC, alan-serrano commented on index.html
> +    <section name="card longitud">
Me parece que es mejor que este sea un div, ya que no es una sección. Encapsular todo este card, en una <section> que tenga como clase cards. Y encapsular todo lo anterior en un <main>

```html
  <main>
    <section class="cards">
      <div class="card longitud">....<div/>
    <section/>
  <main/>
```

2024-02-14 01:40 UTC, oscar-cuellar commented on index.html
> +    <section name="card longitud">
Recomendación aceptada, se modifico el archivo conforme a lo observado.

2024-02-14 01:46 UTC, oscar-cuellar commented on index.html
> +        </div>
Este botón se utiliza para arrojar el resultado automáticamente al realizar la conversión, sin embargo, se esta refactorizando el código, se realizará modificaciones sobre el mismo.

2024-02-14 02:19 UTC, oscar-cuellar commented on src/css/styles.css
> +    width: 216px;
Se procedió con las observaciones, se coloco el valor a "auto".

2024-02-14 02:30 UTC, oscar-cuellar commented on src/css/styles.css
> +    margin: 0 39px 24px 0;
Se procedió con la observación, se utilizo display flex.

2024-02-14 02:31 UTC, oscar-cuellar commented on src/css/styles.css
> +    font-family: inherit;
Se procedió con la observación, se realizaron cambios en el archivo.

2024-02-14 02:31 UTC, oscar-cuellar commented on src/css/styles.css
> +    line-height: 1.1;
Se procedió con la observación, se realizaron cambios en el archivo.

2024-02-14 02:33 UTC, oscar-cuellar commented on src/css/styles.css
> +}
Se tomo la observación, se corrigió el archivo css y html.

2024-02-14 03:37 UTC, alan-serrano commented on index.html
> +        <h3>Quiero convertir:</h3>
Este no es un título, cambiar el h3

2024-02-14 03:37 UTC, alan-serrano commented on index.html
> +        <h3>A:</h3>
Lo mismo aquí

2024-02-14 04:19 UTC, alan-serrano commented on index.html
> +        </div>
```suggestion
        <div class="result"></div>

```

2024-02-14 04:20 UTC, alan-serrano commented on index.html
> +        <h3>Quiero convertir:</h3>
```suggestion
        <div>Quiero convertir:</div>
```

2024-02-14 04:20 UTC, alan-serrano commented on index.html
> +        <h3>A:</h3>
```suggestion
        <div>A:</div>
```

2024-02-14 13:15 UTC, alan-serrano approved these changes
Sólo algunos comentarios

2024-02-14 13:34 UTC, merged